### ISSUE TITLE
Backport 0.6 fixes and non-compat-breaking features.

### ISSUE THREAD

**Issue by KitsuneRal** [quotient-im/libQuotient#391]
- [x] #301, using the code from #383 (but without new API for `RoomCanonicalAlias`)
- [x] #321
- [x] #326 (using `IncorrectRequest` instead of a newly introduced error code)
- [x] #330
- [x] #341 (if possible)
  - [x] #373
  - [x] #376
- [x] #344 (similarly, using `ContentAccessError` to preserve the API)
- [x] #345
- [x] #347
- [x] #358
- [x] #359
- [x] #361
- [x] #365
- [x] #366
- [x] #387
- [x] #388 
  - [x] #386
- [x] #390
Bonus:
- [x] #354
